# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pkUbC8DjLatf2stfp8CTpTJEReUefDoX
"""

frase = 'hello worl'
print(frase + input("digite uma palavra para completar "))

horas = input('digite a hora')
minutos = input('digite os minutos ')
segundos = input('digite os segundos ')

horas == "10"
minutos == "20"
segundos == "03"
      print('horas'+ 'minutos'+ 'segundos' )

      neyJR = input("2303-3336")